#+ endpoint: https://api.krr.triply.cc/datasets/mkumpel/FoodToNonFoodKG/services/FoodToNonFood/sparql

#+ summary: Retrieves all body care products with vegan label
#+ tags: 
#+ - label

PREFIX tax: <http://purl.org/NonFoodKG/product-taxonomy#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX gr: <http://purl.org/goodrelations/v1#>
PREFIX lbl: <http://purl.org/NonFoodKG/label#>

SELECT ?name ?label ?prod WHERE {
    ?product gr:name ?name.
	?product lbl:has_label ?label.
    ?label rdf:type lbl:vegan.
    ?product rdf:type  tax:body_care.
  }