#+ endpoint: https://api.krr.triply.cc/datasets/mkumpel/NonFoodKG/services/NonFoodKG/sparql

#+ summary: Retrieves all body care products with vegan label
#+ tag: label

PREFIX tax: <http://knowrob.org/kg/ProductTaxonomy.owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX lbl: <http://knowrob.org/kg/Label.owl#>


SELECT ?product ?label WHERE {
	?product lbl:has_label ?label.
    ?label rdf:type lbl:vegan.
    ?product owl:sameAs ?prod.
  	?prod rdf:type tax:care_product.
  } 
