#+ endpoint: https://api.krr.triply.cc/datasets/mkumpel/TrustNonFoodKG/services/TrustNonFoodKG/sparql

#+ summary: Retrieves all Deodorants and Linked Data sources
#+ tags: 
#+ - sources

#+ method: POST

PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX tax: <http://knowrob.org/kg/ProductTaxonomy.owl#>
PREFIX log: <http://knowrob.org/kg/Logging.owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

             
        SELECT ?sub ?source ?classsource ?sameclass ?sameclasssource WHERE {
               ?sub rdf:type tax:Deodorants.
               ?sub tax:source ?source.
               tax:Deodorants tax:source ?classsource.
               tax:Deodorants owl:sameAs ?sameclass.
               ?sameclass tax:source ?sameclasssource.
               };
        
insert data { GRAPH log:
                  {<http://grlc.io/api/K4R-IAI/NonFoodKG/SPARQLfiles/> log:called <AllSourcesforDeodorantsandLinkedData>.}
  };  
