#+ endpoint: https://api.krr.triply.cc/datasets/mkumpel/FoodToNonFoodKG/services/FoodToNonFood/sparql

#+ summary: Retrieves all facial care products containing acidic ingredients
#+ tags: 
#+ - ingredients

PREFIX tax: <http://purl.org/NonFoodKG/product-taxonomy#>
PREFIX in: <http://purl.org/NonFoodKG/nonfoodingredient#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX gr: <http://purl.org/goodrelations/v1#>

SELECT ?product ?name ?ingredient WHERE {
  ?product in:has_ingredient ?ingredient.
  ?ingredient rdf:type in:Acid.
  ?product rdf:type tax:facial_care.
  ?product gr:name ?name
} 