#+ endpoint: https://api.krr.triply.cc/datasets/mkumpel/NonFoodKG/services/NonFoodKG/sparql

#+ summary: Retrieves all label for a given EAN
#+ tag: label
#+ tag: ByEAN

PREFIX lbl: <http://knowrob.org/kg/Label.owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>


SELECT ?label WHERE {
	?product lbl:has_EAN ?_EAN.
	?product lbl:has_label ?label.
  } 
