#+ endpoint: https://api.krr.triply.cc/datasets/mkumpel/NonFoodKG/services/NonFoodKG/sparql

#+ summary: Retrieves shelf location for toothpaste with natural ingredients and label "Natrue"
#+ tags: 
#+ - location
#+ - ingredients
#+ - label

PREFIX lbl: <http://purl.org/NonFoodKG/label#>
PREFIX loc: <http://purl.org/NonFoodKG/location#>
PREFIX tax: <http://purl.org/NonFoodKG/product-taxonomy/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX in: <http://purl.org/NonFoodKG/ingredients#>

 select ?shelf ?shelf_floor where {
 ?prod in:has_ingredient ?ingredient.
 ?ingredient rdf:type ?inclass.
 FILTER(?inclass = in:Plant_extract)
 ?prod owl:sameAs ?product.
 ?product rdf:type tax:toothpaste.
 ?sub owl:sameAs ?product.
 ?sub lbl:has_label lbl:Natrue.
 ?product owl:sameAs ?instance.
 ?instance loc:stored_in ?shelf.
 ?instance loc:stored_on ?shelf_floor.
 } GROUP BY ?shelf