#+ endpoint: https://api.krr.triply.cc/datasets/mkumpel/NonFoodKG/services/NonFoodKG/sparql

#+ summary: Retrieves shelf location for cheapest detergent with label "Der gruene Punkt"
#+ tags: 
#+ - location
#+ - label
#+ - price

PREFIX lbl: <http://purl.org/NonFoodKG/label#>
PREFIX loc: <http://purl.org/NonFoodKG/location#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX tax: <http://purl.org/NonFoodKG/product-taxonomy/>
PREFIX in: <http://purl.org/NonFoodKG/ingredients#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?shelf ?shelf_floor ?label WHERE {
  ?product rdf:type tax:detergent.
   ?sub owl:sameAs ?product.
  ?sub lbl:has_label lbl:Der_gruene_Punkt.
  ?product owl:sameAs ?instance.
  ?instance loc:has_price ?price.
  ?instance loc:stored_in ?shelf.
  ?instance loc:stored_on ?shelf_floor.
} ORDER BY ?price