#+ endpoint: https://api.krr.triply.cc/datasets/mkumpel/NonFoodKG/services/NonFoodKG/sparql

#+ summary: Retrieves shelf location for new deodorant with brand "rexona"
#+ tags: 
#+ - location
#+ - flag
#+ - brand

PREFIX brand: <http://purl.org/NonFoodKG/brandinfo#>
PREFIX gr: <http://purl.org/goodrelations/v1#>
PREFIX tax: <http://purl.org/NonFoodKG/product-taxonomy/>
PREFIX loc: <http://purl.org/NonFoodKG/location#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?shelf ?shelf_floor ?brand WHERE {
  ?product rdf:type tax:deodorant.
    ?product owl:sameAs ?ob.
  ?ob gr:hasBrand brand:rexona.
  ?product owl:sameAs ?instance.
  ?instance loc:has_flag "NEU".
  ?instance loc:stored_in ?shelf.
  ?instance loc:stored_on ?shelf_floor.
} GROUP BY ?shelf