#+ endpoint: https://api.krr.triply.cc/datasets/mkumpel/FoodToNonFoodKG/services/FoodToNonFood/sparql

#+ summary: Retrieves shelf location for store brand shampoo without alcohol
#+ tags: 
#+ - location
#+ - brand
#+ - ingredients

PREFIX in: <http://purl.org/NonFoodKG/nonfoodingredient#>
PREFIX gr: <http://purl.org/goodrelations/v1#>
PREFIX brand: <http://purl.org/NonFoodKG/brandinfo#>
PREFIX loc: <http://purl.org/NonFoodKG/location#>
PREFIX lbl: <http://purl.org/NonFoodKG/label#>
PREFIX tax: <http://purl.org/NonFoodKG/product-taxonomy#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?name ?company ?shelf ?shelf_floor ?brand WHERE {
 ?product gr:name ?name.
 ?product in:has_ingredient ?ingredient.
 ?ingredient rdf:type ?inclass.
 FILTER(?inclass != in:Alcohol)
 ?product rdf:type tax:shampoo .
 ?ob gr:hasBrand ?brand.
 ?company brand:has_StoreBrand ?brand.
 ?product loc:stored_in ?shelf.
 ?product loc:stored_on ?shelf_floor.
} GROUP BY ?shelf