#+ endpoint: https://api.krr.triply.cc/datasets/mkumpel/NonFoodKG/services/NonFoodKG/sparql

#+ summary: Retrieves shelf location for new facial care products that are dermatologically tested
#+ tags: 
#+ - location
#+ - flag
#+ - label

PREFIX loc: <http://purl.org/NonFoodKG/location#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX lbl: <http://purl.org/NonFoodKG/label#>
PREFIX tax: <http://purl.org/NonFoodKG/product-taxonomy/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?shelf ?shelf_floor ?label ?brand ?flag WHERE {
  ?product rdf:type tax:facial_care .
  ?ob owl:sameAs ?product.
  ?ob lbl:has_label lbl:Dermatologisch_getestet.
  ?product owl:sameAs ?instance.
  ?instance loc:has_flag "NEU".
  ?instance loc:stored_in ?shelf.
  ?instance loc:stored_on ?shelf_floor.
} GROUP BY ?shelf