#+ endpoint: https://api.krr.triply.cc/datasets/mkumpel/FoodToNonFoodKG/services/FoodToNonFood/sparql

#+ summary: Retrieves shelf location for cheapest shampoo without emulsifier
#+ tags: 
#+ - location
#+ - ingredients
#+ - price

PREFIX in: <http://purl.org/NonFoodKG/nonfoodingredient#>
PREFIX loc: <http://purl.org/NonFoodKG/location#>
PREFIX tax: <http://purl.org/NonFoodKG/product-taxonomy#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX gr: <http://purl.org/goodrelations/v1#>

SELECT DISTINCT ?name ?shelf ?shelf_floor ?price WHERE {
  ?product gr:name ?name.
  ?product in:has_ingredient ?ingredient.
  ?ingredient rdf:type ?inclass.
  FILTER(?inclass != in:Emulsifier) 
  ?product rdf:type tax:shampoo .
  ?product loc:has_price ?price.
  ?product loc:stored_in ?shelf.
  ?product loc:stored_on ?shelf_floor.
} ORDER BY ?price
