#+ endpoint: https://api.krr.triply.cc/datasets/mkumpel/FoodToNonFoodKG/services/FoodToNonFood/sparql

#+ summary: Retrieves shelf location for cheapest bodylotion that are dermatologically tested
#+ tags: 
#+ - location
#+ - price
#+ - label

PREFIX lbl: <http://purl.org/NonFoodKG/label#>
PREFIX loc: <http://purl.org/NonFoodKG/location#>
PREFIX tax: <http://purl.org/NonFoodKG/product-taxonomy#>
PREFIX gr: <http://purl.org/goodrelations/v1#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?name ?shelf ?shelf_floor ?price WHERE {
  ?product gr:name ?name.
  ?product rdf:type tax:bodylotion .
  ?product lbl:has_label lbl:Dermatologisch_getestet.
  ?product loc:has_price ?price.
  ?product loc:stored_in ?shelf.
  ?product loc:stored_on ?shelf_floor.
} ORDER BY ?price