#+ endpoint: https://api.krr.triply.cc/datasets/mkumpel/FoodToNonFoodKG/services/FoodToNonFood/sparql

#+ summary: Retrieves shelf location for new store brand products of type medication
#+ tags: 
#+ - location
#+ - flag
#+ - brand

PREFIX brand: <http://purl.org/NonFoodKG/brandinfo#>
PREFIX gr: <http://purl.org/goodrelations/v1#>
PREFIX loc: <http://purl.org/NonFoodKG/location#>
PREFIX tax: <http://purl.org/NonFoodKG/product-taxonomy#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?name ?company ?shelf ?shelf_floor WHERE {
  ?product gr:name ?name.
  ?product rdf:type tax:medication.
  ?product gr:hasBrand ?brand.
  ?company brand:has_StoreBrand ?brand.
  ?product loc:has_flag "NEU".
  ?product loc:stored_in ?shelf.
  ?product loc:stored_on ?shelf_floor.
} GROUP BY ?shelf