#+ endpoint: https://api.krr.triply.cc/datasets/mkumpel/FoodToNonFoodKG/services/FoodToNonFood/sparql

#+ summary: Retrieves all products with organic label
#+ tags:
#+  - label

PREFIX gr: <http://purl.org/goodrelations/v1#>
PREFIX in: <http://purl.org/NonFoodKG/nonfoodingredient#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT DISTINCT ?product ?name WHERE {
  ?ingredient rdf:type in:organic.
  ?product in:has_ingredient ?ingredient.
  ?product gr:name ?name.
} 
