#+ endpoint: https://api.krr.triply.cc/datasets/mkumpel/NonFoodKG/services/NonFoodKG/sparql

#+ summary: Retrieves all product classes for a given EAN
#+ tag: ByEAN

PREFIX lbl: <http://knowrob.org/kg/Label.owl#>
PREFIX info: <http://knowrob.org/kg/ProductInfo.owl#>
PREFIX tax: <http://knowrob.org/kg/ProductTaxonomy.owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>


SELECT ?prod ?class ?name WHERE {
    ?prod tax:has_EAN ?_EAN.
    ?prod rdf:type ?class.
    FILTER (?class != owl:NamedIndividual && ?class != tax:Product)
    ?product owl:sameAs ?prod.
  	?product lbl:has_name ?name.
  } 
