#+ endpoint: https://api.krr.triply.cc/datasets/mkumpel/FoodToNonFoodKG/services/FoodToNonFood/sparql

#+ summary: Retrieves location for cheapest baby food (ordered by price)
#+ tags: 
#+ - location
#+ - price

PREFIX loc: <http://purl.org/NonFoodKG/location#>
PREFIX tax: <http://purl.org/NonFoodKG/product-taxonomy#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX gr: <http://purl.org/goodrelations/v1#>

SELECT ?name ?shelf ?shelf_floor ?price WHERE {
  ?product gr:name ?name.
  ?product rdf:type tax:baby_food.
  ?product loc:stored_in ?shelf.
  ?product loc:stored_on ?shelf_floor.
  ?product loc:has_price ?price.
} ORDER BY ?price