#+ endpoint: https://api.krr.triply.cc/datasets/mkumpel/ProductCatalog/services/FoodToNonFood/sparql

#+ summary: Retrieves location for cheapest baby food (ordered by price)
#+ tags: 
#+ - location
#+ - price

PREFIX loc: <http://knowrob.org/kg/location.owl#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX tax: <http://knowrob.org/kb/product-taxonomy.owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>


SELECT ?product ?shelf ?shelf_floor ?price WHERE {
  ?product rdf:type tax:baby_food.
  ?product owl:sameAs ?prod.
  ?prod loc:stored_in ?shelf.
  ?prod loc:stored_on ?shelf_floor.
  ?prod loc:has_price ?price.
} ORDER BY ?price