#+ endpoint: https://api.krr.triply.cc/datasets/mkumpel/ProductCatalog/services/FoodToNonFood/sparql

#+ summary: Retrieves location for store brand juice
#+ tags: 
#+ - location
#+ - brand

PREFIX gr: <http://purl.org/goodrelations/v1#>
PREFIX brand: <http://purl.org/NonFoodKG/brandinfo#>
PREFIX loc: <http://purl.org/NonFoodKG/location#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX tax: <http://purl.org/NonFoodKG/product-taxonomy#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?name ?shelf ?shelf_floor ?brand WHERE {
  ?product gr:name ?name.
  ?product rdf:type tax:juice.
  ?product gr:hasBrand ?brand.
  brand:dm brand:has_StoreBrand ?brand.
  ?product loc:stored_in ?shelf.
  ?product loc:stored_on ?shelf_floor.
} 