#+ endpoint: https://api.krr.triply.cc/datasets/mkumpel/NonFoodKG/services/NonFoodKG/sparql

#+ summary: Retrieves shelf location for detergent
#+ tag: location

PREFIX tax: <http://knowrob.org/kg/ProductTaxonomy.owl#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX loc: <http://knowrob.org/kg/ProductToShelf.owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?shelf WHERE {
  ?product rdf:type ?_class.
  ?product owl:sameAs ?prod.
  ?prod loc:stored_in ?shelf.
} 
