#+ endpoint: https://api.krr.triply.cc/datasets/mkumpel/FoodToNonFoodKG/services/FoodToNonFood/sparql

#+ summary: Retrieves shelf location for detergent
#+ tags: 
#+ - location

PREFIX tax: <http://purl.org/NonFoodKG/product-taxonomy#>
PREFIX loc: <http://purl.org/NonFoodKG/location#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX gr: <http://purl.org/goodrelations/v1#>

SELECT DISTINCT ?name ?shelf WHERE {
  ?product gr:name ?name.
  ?product rdf:type tax:detergent.
  ?product loc:stored_in ?shelf.
} 