#+ endpoint: https://api.krr.triply.cc/datasets/mkumpel/ProductCatalog/services/FoodToNonFood/sparql

#+ summary: Retrieves location for toothpaste containing only natural ingredients
#+ tags: 
#+ - location
#+ - ingredients

PREFIX loc: <http://purl.org/NonFoodKG/location#>
PREFIX in: <http://purl.org/NonFoodKG/nonfoodingredient#>
PREFIX gr: <http://purl.org/goodrelations/v1#>
PREFIX tax: <http://purl.org/NonFoodKG/product-taxonomy#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?name ?shelf ?shelf_floor WHERE {
  ?product gr:name ?name.
  ?product in:has_ingredient ?ingredient.
  ?ingredient rdf:type ?inclass.
  FILTER(?inclass = in:Plant_extract)
  ?product rdf:type tax:toothpaste.
  ?product loc:stored_in ?shelf.  
  ?product loc:stored_on ?shelf_floor.
} GROUP BY ?product